FROM python:3.11-slim

WORKDIR /app

COPY server/requirements.txt .
RUN pip install -r requirements.txt
RUN python -m livekit.plugins.turn_detector.download_model

COPY server/ .

CMD ["python", "app/agent_orchestrator.py", "start"]
